project:
  type: book

execute:
  cache: false
#  freeze: auto  # re-render only when source changes


book:
  title: "R 과 Quarto 를 이용한 데이터 테이블 작성" 
  subtitle: "서울시립대학교 빅데이터 혁신융합대학 사업단"
  author: "서울시립대학교 통계학과 이용희, 정영두"
  date: "1/29/2025"
  downloads: [pdf]
  
  chapters:
    - index.qmd
    - docs/chapter-00.qmd
    - docs/chapter-01.qmd
    - docs/chapter-02.qmd
    - docs/chapter-03.qmd
    - docs/appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    lang: ko 
    language: _language.yml
    code-fold: true
    code-overflow: wrap
    embed-resources: false
    toc: true
    toc-depth: 3
    number-depth: 2
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    fig-cap-location: top
    crossref:
      fig-title: "그림"
      tbl-title: "표"
      fig-prefix: "그림" # (default is "Figure")
      tbl-prefix: '' #표    # (default is "Table")
      eq-prefix:  '' #식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    css: styles.css
    include-in-header:
      - text: |
          <script type="text/javascript">
           window.MathJax = {
            tex: {
              macros: {
              RR: '{\\mathbb R}',                    // a simple string replacement
              hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
              bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
              pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
              pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2]
            },
            environments: {
            braced: ["\\left\\{", "\\right\\}"]
            }
           }
          };
          </script>
#    include-in-header:
#      - latex/preamble-mathjax.tex
  pdf:
    documentclass: scrbook
    classoption: oneside
    papersize: A4
# 오류 발생     lang: ko
    fontsize: 10pt
    lof: true
    lot: true
    toc-depth: 2
    number-depth: 2
    code-overflow: wrap
    language: _language.yml
    latex-auto-install: true
    latex-tinytex: true
    pdf-engine: xelatex
    crossref:
      fig-title: "그림"
      tbl-title: "표"
      fig-prefix:  "그림" # (default is "Figure")
      tbl-prefix: '' #표    # (default is "Table")
      eq-prefix:  '' #식     # (default is "Equation")
      ref-hyperlink: true # (default is true)
    include-in-header: latex/preamble.tex
