# 개요 {.unnumbered}


## 목표 및 개요

이 강의 교재는 R과 Quarto를 활용하여 데이터 테이블을 자동으로 작성하는 방법을 학습하는 것을 목표로 한다. 주요 내용은 다음과 같다.

- 결측값 분석 및 처리  
  - 데이터에서 결측값을 탐색하고, 결측값을 적절히 대체하는 다양한 방법을 학습
- R을 이용한 보고서용 데이터 테이블 작성  
  - `tidyverse` 패키지를 활용하여 데이터를 정리하고, 다양한 형식의 통계 테이블을 생성하는 방법을 소개
- 고급 품질의 테이블 생성  
  - `flextable` 패키지를 사용하여 보고서에 적합한 고급 품질의 테이블을 만드는 기술을 학습
- 다양한 문서 형식으로의 변환  
  - Quarto를 활용하여 테이블을 포함한 보고서를 MS Word, PDF, MS Excel 등의 다양한 문서 형식으로 변환하는 방법을 소개

## 내용 요약 및 범위

- 결측값에 대한 기초 분석과 기본적인 대체방법에 대하여 소개  
- `R` 언어로 보고서용 데이터 테이블을 자동으로 작성하는 방법 소개
- `flextable` 패키지를 이용하여 고급 품질의 테이블 작성 방법 소개
- 테이블을 포함한 보고서를 다양한 형식(MS Word, PDF, MS Excel)으로 생성하는 방법 소개  

## 활용범위 및 기대효과

이 강의에서 다루는 내용은 다음과 같은 분야에서 활용될 수 있다:

- 데이터 분석 및 보고서 작성  
  - 연구자, 분석가, 데이터 과학자들이 데이터를 정리하고 분석하여 재현 가능한 보고서를 작성하는 데 유용
- 공공기관 및 기업의 통계 업무  
  - 공공기관 및 기업에서 데이터를 체계적으로 관리하고 통계 보고서를 자동화하는 데 활용
- 과학적 연구 및 논문 작성  
  - 연구 논문에서 사용되는 데이터 요약 테이블을 효율적으로 생성하고, 재현 가능한 연구 환경을 구축하는 데 적용
  
이 강의에 의한 기대효과는 다음과 같다. 

- 자동화된 데이터 처리  
  - 데이터를 수작업으로 정리하는 대신, R 코드로 자동화하여 반복 작업을 줄이고 생산성을 향상
- 재현 가능성 보장  
  - 분석 과정이 R 코드로 문서화되므로, 동일한 데이터 및 분석 조건에서 언제든지 동일한 결과를 재현
- 고품질 문서 작성  
  - `flextable`과 Quarto를 활용하여 시각적으로 우수한 품질의 테이블과 보고서를 작성
- 데이터 분석의 효율성 증가  
  - 데이터 요약, 통계 분석, 시각화를 하나의 워크플로우로 통합하여 데이터 활용의 효율성을 극대화


## 분석에 필요한 것들

::: {.callout-important}

### 필요한 선행 지식

이 교과서를 공부하기 위해서는 다음과 같은 선행지식이 필요합니다.

1. `R` 언어의 기초: 기본적인 프로그래밍의 문법, 패키지 사용, `data.frame` 에 대한 정의 및 기초,   
2. 기초 통계학: 연속형 자료와 범주형 자료에 대한 요약 통계량(평균, 표준편차, 비율 등 ), 회귀분석의 기초 

:::

### 교과서 홈페이지

이 교과서의 내용은 [온라인 홈페이지](https://uos-bigdata.github.io/reporttable/) 에 있다.

### 응용 프로그램 

- [`R`](https://www.r-project.org/): 데이터 사이언스를 위한 컴퓨터 언어
- [`Rstudio`](https://posit.co/download/rstudio-desktop/) : R 언어를 사용하기 위한 GUI
- [`Quarto`](https://quarto.org/) 는 오픈소스로 공개된 과학기술 분야의 출판 시스템니다 (@Allaire_Quarto_2024 참고)

### R 패키지 

이 책애서 사용하는 `R` 패키지는 다음과 같다.


```r
library(here)
library(tidyverse)
library(knitr)
library(kableExtra)

library(DescTools)
library(mice)
library(ggmice)
library(naniar)

library(flextable)
library(officer)
library(gtsummary)
library(arsenal)

library(showtext)
```

### 예제 자료  


#### 국민체력100 측정자료 

  - 출처: [문화빅데이터 프랫폼 - 서울올림픽기념국민체육진흥공단](https://www.bigdata-culture.kr/bigdata/user/data_market/detail.do?id=ace0aea7-5eee-48b9-b616-637365d665c1)

  - 데이터 소개
    - 서울올림픽기념 국민체육진흥공단에서 관리하고 있는 국민체력측정데이터의 항목별 측정 정보를 제공하는 데이터
    - 체력측정 센터명, 연령대, 신장, 체중, 윗몸일으키기, BMI, 제자리 멀리뛰기 등의 체력측정 항목별 결과를 조회 가능

#### 2019년 서울특별시 부동산 실거래가 자료

  - 출처: [서울 열린데이터 광장](https://data.seoul.go.kr/dataList/OA-21275/S/1/datasetView.do)

  - 데이터 소개
    - 서울 열린 데이터 광장에서 2019년 서울특별시 부동산 실거래가 정보를 가진 자료
    - 2019년 거래하여 신고한 주택들의 위치와 정보 그리고 실거래 가격이 포함된 총 67238건의 거래자료 중 일부 자료와 함성자료 